
export const LOGIN = "LOGIN"
export const SIGNOUT = "SIGNOUT"

export const GET_PRODUCTS_PENDING = "GET_PRODUCTS_PENDING"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE "

export const ADD_TO_CART = "ADD_TO_CART"
export const UPDATE_CART =  "UPDATE_CART"
export const REMOVE_FROM_CART =  "REMOVE_FROM_CART"
export const CHECKOUT = "CHECKOUT"
export const SET_DELIVERY_CHOICE = "SET_DELIVERY_CHOICE"

export const SET_PAGE_INDEX = 'SET_PAGE_INDEX'